Description: Postcode Web App CloudFormation template
Resources:
    MyS3Bucket:
        Type: AWS::S3::Bucket
        Properties:
            BucketName: postcode-webapp
            AccessControl: PublicRead
            WebsiteConfiguration:
                IndexDocument: index.html
    MyS3BucketPolicy:
        Type: AWS::S3::BucketPolicy
        Properties: 
            PolicyDocument: 
                Statement: 
                  - Effect: Allow
                    Principal: "*"
                    Action:
                      - s3:GetObject
                    Resource: !Sub 'arn:aws:s3:::${MyS3Bucket}/*'
            Bucket: !Ref MyS3Bucket